#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Execute a grasp motion on the Feetech bus.

Default mode keeps the original fixed soft J-shape motion.
Plan mode reads grasp_plan.json generated by grasp_planning.py and sends
relative step deltas for each planned six-angle waypoint.
"""

from __future__ import annotations

import argparse
import json
import sys
import threading
import time
from pathlib import Path

import numpy as np

try:
    import serial
except ImportError:
    print("Please install pyserial: pip install pyserial")
    sys.exit(1)


HEADER = bytes([0xFF, 0xFF])
DEFAULT_SPEED = 40
JSHAPE_VEC_1 = [-5000, 0, 0, 0, 3000, 0]
JSHAPE_VEC_2 = [-2000, 0, 0, 0, 1000, 0]
HOLD_AFTER_VEC1_S = 5.0
HOLD_BEFORE_HOME_S = 10.0
START_DELAY_S = 5.0
DEFAULT_WAYPOINT_DELAY_S = 0.04
DEFAULT_MIN_STEP_DELTA = 3
DEFAULT_SERVO_MAX_ITERS = 4
DEFAULT_SERVO_SUCCESS_GAP_MM = 10.0
DEFAULT_SERVO_MAX_ANGLE_DEG = 12.0
DEFAULT_GRASP_HOLD_S = 10.0
# --- 绳驱 / PCC 参考系（用户实机经验 + marker CSV）---
# 原始 PCC 参考弯曲平面为 XOY；每根绳的 +步进沿固定 phi 方向增加曲率:
#   motor1+ -> -X, phi=180° (仍在 XOY 内)
#   motor2+ -> -Z, phi=270° (相对 XOY 转到 ZOY 平面)
# 倒立臂主轴沿 +Y，与 XOY 的对应关系: 侧向弯曲平面为 XZ（X 同轴，Z 取代“出平面”方向）:
#   u_xz(phi) = [cos(phi), sin(phi)]  分量依次为 (X, Z)
#   phi=0° -> +X, 90° -> +Z, 180° -> -X, 270° -> -Z
#   delta_bend_xz = sum_k (motor_k_steps / steps_per_deg) * u_xz(phi_k)
# marker CSV 的 Plane 角与绳组 phi 差 270°（见 rope_phi_to_marker_plane_deg）。
#
# Section | Motors   | phi (°) | +motor 弯曲沿 (XZ)
# --------|----------|---------|-------------------
#    1    | 6, 3     | 0, 270  | +X, -Z
#    2    | 5, 2     | 0, 270  | +X, -Z
#    3    | 1, 4     | 180,270 | -X, -Z
DEFAULT_SECTION_STEP_LIMITS = [8000, 4000, 4000, 8000, 4000, 4000]
# (planner plane index, planner PCC theta index, motor_a, motor_b, phi_a_deg, phi_b_deg)
SECTION_ROPE_PAIRS = [
    (0, 3, 6, 3, 0.0, 270.0),
    (1, 4, 5, 2, 0.0, 270.0),
    (2, 5, 1, 4, 180.0, 270.0),
]
SEGMENT_LENGTHS_MM = np.array([150.0, 150.0, 150.0], dtype=float)
# GP_tennis / inverse-J CSV：存储的 PCC_Theta 乘此符号后参与 PCC 积分
INVERTED_PCC_THETA_SIGN = -1.0
# v2 绳组 IK 写入的 Theta 与 bend_xz=theta*u(phi) 同号，正运动学用 +1
ROPE_PLANNER_THETA_SIGN = 1.0
MARKER_PLANE_OFFSET_FROM_ROPE_PHI_DEG = 270.0
# motor_id -> +步进时 u_xz(phi) 的方向 (°)
MOTOR_POSITIVE_PULL_PHI_DEG: dict[int, float] = {
    1: 180.0,
    2: 270.0,
    3: 270.0,
    4: 270.0,
    5: 0.0,
    6: 0.0,
}
# soft_arm_center (视觉) -> 臂系: 原先把“前向”当成 Y，实际前向为 -Z
DEFAULT_VISION_TO_ARM_SCALE = np.array([1.0, 1.0, 1.0], dtype=float)
DEFAULT_ARM_BASE_MM = np.array([0.0, 0.0, 0.0], dtype=float)
# Section-3 grasp rope range (steps, absolute value per motor):
#   6500 < |m| < 8000,  |m1| + |m4| < 15000
MOTOR14_MIN_ABS_STEPS = 6500
MOTOR14_MAX_ABS_STEPS = 8000
MOTOR14_MAX_SUM_ABS_STEPS = 15000
DEFAULT_REF_STEPS_PER_DEGREE = 100.0
# Kinematic default: max feasible bend ~45° between +X and -Y (not tied to GP demo).
REF_GRASP_MOTOR1_STEPS = -7500
REF_GRASP_MOTOR4_STEPS = 7400
MAX_MOTOR14_ABS_STEPS = MOTOR14_MAX_ABS_STEPS
SECTION3_PHI_IDX = 2
SECTION3_THETA_IDX = 5
SECTION3_ROPE_PHI1_DEG = 180.0
SECTION3_ROPE_PHI4_DEG = 270.0
# Sections 1-2 mainly set approach direction; section 3 closes the grasp.
MAX_SECTION12_POSE_DELTA = np.array([22.0, 22.0, 0.0, 28.0, 28.0, 0.0], dtype=float)
SECTION12_PHI_OFFSET_DEG = 0.0


def vision_center_to_arm_mm(
    center_mm: np.ndarray,
    scale: np.ndarray | None = None,
) -> np.ndarray:
    """
    soft_arm_center (视觉 JSON, mm) -> 臂基坐标系.

    臂系: +X 侧向, +Y 向下, -Z 朝相机; 勿再把前向误当成 +Y.
    默认 scale=[1,1,1]；若视觉 Z 与臂 -Z 反号，设 scale[2]=-1.
    """
    center_mm = np.asarray(center_mm, dtype=float).reshape(3)
    if scale is None:
        scale = DEFAULT_VISION_TO_ARM_SCALE
    return center_mm * np.asarray(scale, dtype=float)


def motor_pull_unit_xz(phi_deg: float) -> np.ndarray:
    """+motor 步进在 XZ 弯曲平面内的单位方向 u(phi) = [cos(phi), sin(phi)]。"""
    r = np.deg2rad(float(phi_deg))
    return np.array([np.cos(r), np.sin(r)], dtype=float)


def _motor_unit_2d(phi_deg: float) -> np.ndarray:
    return motor_pull_unit_xz(phi_deg)


def motor_steps_to_bend_delta_xz(
    motor_steps: dict[int, int] | list[int],
    steps_per_degree: float = DEFAULT_REF_STEPS_PER_DEGREE,
) -> np.ndarray:
    """多电机步进合成的 XZ 弯曲增量 [dX, dZ]（度·方向）。"""
    delta = np.zeros(2, dtype=float)
    if isinstance(motor_steps, dict):
        items = motor_steps.items()
    else:
        items = ((i + 1, motor_steps[i]) for i in range(min(6, len(motor_steps))))
    for motor_id, steps in items:
        phi = MOTOR_POSITIVE_PULL_PHI_DEG.get(int(motor_id))
        if phi is None:
            continue
        dtheta = float(steps) / float(steps_per_degree)
        delta += dtheta * motor_pull_unit_xz(phi)
    return delta


def rope_phi_to_marker_plane_deg(phi_rope_deg: float) -> float:
    """绳组 XZ 平面 phi -> CSV Plane* 列（GP marker / XOY 约定）。"""
    return (float(phi_rope_deg) + MARKER_PLANE_OFFSET_FROM_ROPE_PHI_DEG) % 360.0


def marker_plane_to_rope_phi_deg(phi_marker_deg: float) -> float:
    """CSV Plane* -> 绳组 XZ phi。"""
    return (float(phi_marker_deg) - MARKER_PLANE_OFFSET_FROM_ROPE_PHI_DEG) % 360.0


def bend_dir_3d_inverted_from_phi(phi_deg: float, tangent: np.ndarray) -> np.ndarray:
    """
    倒立臂 PCC：弯曲平面 XZ，方向 [cos(phi), 0, sin(phi)]，投影到法平面。
    主切线沿 +Y；勿用 GP 正立系 [sin(phi), cos(phi), 0]。
    """
    beta = np.deg2rad(float(phi_deg))
    plane_dir = np.array([np.cos(beta), 0.0, np.sin(beta)], dtype=float)
    bend_dir = plane_dir - float(np.dot(plane_dir, tangent)) * tangent
    norm = float(np.linalg.norm(bend_dir))
    if norm < 1e-9:
        fallback = np.array([1.0, 0.0, 0.0], dtype=float)
        bend_dir = fallback - float(np.dot(fallback, tangent)) * tangent
        norm = float(np.linalg.norm(bend_dir))
    return bend_dir / max(norm, 1e-12)


def fk_inverted_pcc_centerline(
    pose_deg: np.ndarray,
    base_mm: np.ndarray | None = None,
    segment_lengths_mm: np.ndarray | None = None,
    *,
    theta_sign: float = ROPE_PLANNER_THETA_SIGN,
    points_per_segment: int = 16,
) -> np.ndarray:
    """
    倒立软体臂绳组 PCC 正运动学（臂系: +Y 主轴，XZ 弯曲）。

    pose: [Plane1, Plane2, Plane3, Theta1, Theta2, Theta3]（绳组 phi，非 CSV 原值）
    """
    if base_mm is None:
        base_mm = DEFAULT_ARM_BASE_MM
    if segment_lengths_mm is None:
        segment_lengths_mm = SEGMENT_LENGTHS_MM

    pose_deg = np.asarray(pose_deg, dtype=float)
    base_mm = np.asarray(base_mm, dtype=float).reshape(3)
    segment_lengths_mm = np.asarray(segment_lengths_mm, dtype=float)

    phi_deg = pose_deg[0:3]
    theta_deg = pose_deg[3:6] * float(theta_sign)

    pts: list[np.ndarray] = [base_mm.copy()]
    position = base_mm.copy()
    tangent = np.array([0.0, 1.0, 0.0], dtype=float)

    for seg_i in range(3):
        alpha = np.deg2rad(float(theta_deg[seg_i]))
        length = float(segment_lengths_mm[seg_i])
        bend_dir = bend_dir_3d_inverted_from_phi(float(phi_deg[seg_i]), tangent)

        for i in range(1, points_per_segment + 1):
            frac = i / points_per_segment
            alpha_i = alpha * frac
            length_i = length * frac
            if abs(alpha) < 1e-9:
                point = position + tangent * length_i
            else:
                radius = length / alpha
                point = (
                    position
                    + radius * np.sin(alpha_i) * tangent
                    + radius * (1.0 - np.cos(alpha_i)) * bend_dir
                )
            pts.append(point.copy())

        if abs(alpha) < 1e-9:
            position = position + tangent * length
        else:
            radius = length / alpha
            position = (
                position
                + radius * np.sin(alpha) * tangent
                + radius * (1.0 - np.cos(alpha)) * bend_dir
            )
            tangent = np.cos(alpha) * tangent + np.sin(alpha) * bend_dir
            tangent = tangent / max(float(np.linalg.norm(tangent)), 1e-12)

    return np.asarray(pts, dtype=float)


def _planned_bend_xz(pose: np.ndarray, phi_idx: int, theta_idx: int) -> np.ndarray:
    """XZ 弯曲向量 [X分量, Z分量] = theta * u(phi)。"""
    phi_deg = float(pose[phi_idx])
    theta_deg = float(pose[theta_idx])
    return float(theta_deg) * motor_pull_unit_xz(phi_deg)


def _planned_bend_xy(pose: np.ndarray, phi_idx: int, theta_idx: int) -> np.ndarray:
    """Backward-compatible alias (bend in XZ for inverted arm)."""
    return _planned_bend_xz(pose, phi_idx, theta_idx)


def _decompose_bend_2d_to_rope_thetas(
    delta_bend_2d: np.ndarray,
    phi_a_deg: float,
    phi_b_deg: float,
) -> tuple[float, float]:
    """Solve delta_bend = dtheta_a * u(phi_a) + dtheta_b * u(phi_b) in XZ."""
    m = np.column_stack([_motor_unit_2d(phi_a_deg), _motor_unit_2d(phi_b_deg)])
    dtheta_a, dtheta_b = np.linalg.solve(m, np.asarray(delta_bend_2d, dtype=float))
    return float(dtheta_a), float(dtheta_b)


def _decompose_bend_xy_to_rope_thetas(
    delta_bend_xy: np.ndarray,
    phi_a_deg: float,
    phi_b_deg: float,
) -> tuple[float, float]:
    return _decompose_bend_2d_to_rope_thetas(delta_bend_xy, phi_a_deg, phi_b_deg)


def _theta_delta_to_step(delta_theta_deg: float, scale: float, min_step_delta: int) -> int:
    step = int(round(delta_theta_deg * scale))
    if abs(step) < min_step_delta:
        return 0
    return step


def make_rope_home_pose(home_pose: np.ndarray) -> np.ndarray:
    """Motor step zero reference: demo home with section-3 plane/theta cleared."""
    rope = np.asarray(home_pose, dtype=float).copy()
    rope[SECTION3_PHI_IDX] = 0.0
    rope[SECTION3_THETA_IDX] = 0.0
    return rope


def section3_bend_xz(pose: np.ndarray) -> np.ndarray:
    return _planned_bend_xz(pose, SECTION3_PHI_IDX, SECTION3_THETA_IDX)


def section3_bend_yz(pose: np.ndarray) -> np.ndarray:
    """Deprecated alias kept for older call sites; returns XZ bend."""
    return section3_bend_xz(pose)


def section3_bend_xy(pose: np.ndarray) -> np.ndarray:
    return section3_bend_xz(pose)


def section3_rope_thetas_from_home(
    home_pose: np.ndarray,
    pose: np.ndarray,
) -> tuple[float, float]:
    delta_bend = section3_bend_xy(pose) - section3_bend_xy(home_pose)
    return _decompose_bend_xy_to_rope_thetas(
        delta_bend, SECTION3_ROPE_PHI1_DEG, SECTION3_ROPE_PHI4_DEG
    )


def section3_rope_steps_from_home(
    home_pose: np.ndarray,
    pose: np.ndarray,
    steps_per_degree: float = DEFAULT_REF_STEPS_PER_DEGREE,
) -> tuple[int, int]:
    dtheta1, dtheta4 = section3_rope_thetas_from_home(home_pose, pose)
    return (
        int(round(dtheta1 * steps_per_degree)),
        int(round(dtheta4 * steps_per_degree)),
    )


def motor14_in_grasp_range(motor1_steps: int, motor4_steps: int) -> bool:
    """Valid section-3 grasp: each motor engaged, sum of pulls below 15000."""
    a1, a4 = abs(int(motor1_steps)), abs(int(motor4_steps))
    return (
        a1 > MOTOR14_MIN_ABS_STEPS
        and a1 < MOTOR14_MAX_ABS_STEPS
        and a4 > MOTOR14_MIN_ABS_STEPS
        and a4 < MOTOR14_MAX_ABS_STEPS
        and (a1 + a4) < MOTOR14_MAX_SUM_ABS_STEPS
    )


def motor14_grasp_penalty(motor1_steps: int, motor4_steps: int) -> float:
    """Soft penalty when motor1/4 leave the feasible grasp envelope."""
    a1, a4 = abs(int(motor1_steps)), abs(int(motor4_steps))
    penalty = 0.0
    for a in (a1, a4):
        if a <= MOTOR14_MIN_ABS_STEPS:
            penalty += 420.0 * (MOTOR14_MIN_ABS_STEPS + 1 - a)
        if a >= MOTOR14_MAX_ABS_STEPS:
            penalty += 420.0 * (a - MOTOR14_MAX_ABS_STEPS + 1)
    sum_abs = a1 + a4
    if sum_abs >= MOTOR14_MAX_SUM_ABS_STEPS:
        penalty += 520.0 * (sum_abs - MOTOR14_MAX_SUM_ABS_STEPS + 1)
    return penalty


def motor14_steps_to_bend_delta(
    motor1_steps: int,
    motor4_steps: int,
    steps_per_degree: float = DEFAULT_REF_STEPS_PER_DEGREE,
) -> np.ndarray:
    """motor1+ @180°->-X, motor4+ @270°->-Z；返回 XZ 弯曲增量。"""
    return motor_steps_to_bend_delta_xz(
        {1: motor1_steps, 4: motor4_steps},
        steps_per_degree=steps_per_degree,
    )


def bend_delta_to_motor14_steps(
    delta_bend_xy: np.ndarray,
    steps_per_degree: float = DEFAULT_REF_STEPS_PER_DEGREE,
) -> tuple[int, int]:
    dtheta1, dtheta4 = _decompose_bend_xy_to_rope_thetas(
        np.asarray(delta_bend_xy, dtype=float),
        SECTION3_ROPE_PHI1_DEG,
        SECTION3_ROPE_PHI4_DEG,
    )
    return (
        int(round(dtheta1 * steps_per_degree)),
        int(round(dtheta4 * steps_per_degree)),
    )


def project_motor14_to_grasp_range(motor1_steps: int, motor4_steps: int) -> tuple[int, int]:
    """Scale/clamp motor steps into (6500,8000) each with |m1|+|m4| < 15000."""
    m1, m4 = int(motor1_steps), int(motor4_steps)
    if m1 == 0 and m4 == 0:
        return REF_GRASP_MOTOR1_STEPS, REF_GRASP_MOTOR4_STEPS

    for _ in range(24):
        a1, a4 = abs(m1), abs(m4)
        if a1 == 0 and a4 == 0:
            return REF_GRASP_MOTOR1_STEPS, REF_GRASP_MOTOR4_STEPS

        if a1 + a4 >= MOTOR14_MAX_SUM_ABS_STEPS:
            scale = (MOTOR14_MAX_SUM_ABS_STEPS - 1) / max(a1 + a4, 1)
            m1 = int(round(m1 * scale))
            m4 = int(round(m4 * scale))
            continue

        changed = False
        if a1 <= MOTOR14_MIN_ABS_STEPS:
            m1 = int(round(np.sign(m1) or -1) * (MOTOR14_MIN_ABS_STEPS + 1))
            changed = True
        if a4 <= MOTOR14_MIN_ABS_STEPS:
            m4 = int(round(np.sign(m4) or 1) * (MOTOR14_MIN_ABS_STEPS + 1))
            changed = True
        if a1 >= MOTOR14_MAX_ABS_STEPS:
            m1 = int(round(np.sign(m1) or -1) * (MOTOR14_MAX_ABS_STEPS - 1))
            changed = True
        if a4 >= MOTOR14_MAX_ABS_STEPS:
            m4 = int(round(np.sign(m4) or 1) * (MOTOR14_MAX_ABS_STEPS - 1))
            changed = True
        if not changed:
            break
    return m1, m4


def maximize_motor14_for_bend_direction(
    dir_2d: np.ndarray,
    steps_per_degree: float = DEFAULT_REF_STEPS_PER_DEGREE,
) -> tuple[int, int]:
    """Pick motor1/4 in grasp range to maximize bend along dir_2d in XZ."""
    dir_2d = np.asarray(dir_2d, dtype=float).reshape(2)
    norm = float(np.linalg.norm(dir_2d))
    if norm < 1e-9:
        dir_2d = np.array([0.0, -1.0], dtype=float)
    else:
        dir_2d = dir_2d / norm

    dtheta1, dtheta4 = _decompose_bend_2d_to_rope_thetas(
        dir_2d, SECTION3_ROPE_PHI1_DEG, SECTION3_ROPE_PHI4_DEG
    )
    if abs(dtheta1) < 1e-9 and abs(dtheta4) < 1e-9:
        return REF_GRASP_MOTOR1_STEPS, REF_GRASP_MOTOR4_STEPS

    scale = float("inf")
    for dtheta in (dtheta1, dtheta4):
        if abs(dtheta) < 1e-9:
            continue
        scale = min(scale, (MOTOR14_MAX_ABS_STEPS - 1) / (abs(dtheta) * steps_per_degree))
    scale = min(scale, (MOTOR14_MAX_SUM_ABS_STEPS - 1) / (abs(dtheta1) + abs(dtheta4)) / steps_per_degree)

    m1 = int(round(dtheta1 * scale * steps_per_degree))
    m4 = int(round(dtheta4 * scale * steps_per_degree))
    return project_motor14_to_grasp_range(m1, m4)


def _ball_dir_yz_arm(
    ball_center_mm: np.ndarray,
    base_mm: np.ndarray | None = None,
    approach: str = "side",
    vision_to_arm_scale: np.ndarray | None = None,
) -> np.ndarray:
    """Deprecated name; returns unit direction in XZ bend plane toward the ball."""
    ball_arm = vision_center_to_arm_mm(ball_center_mm, vision_to_arm_scale)
    if base_mm is None:
        base_arm = DEFAULT_ARM_BASE_MM.copy()
    else:
        base_arm = vision_center_to_arm_mm(base_mm, vision_to_arm_scale)
    if approach == "top-down":
        return np.array([0.0, 0.0], dtype=float)
    if approach == "below":
        return np.array([0.0, 0.0], dtype=float)

    dir_xz = np.array(
        [ball_arm[0] - base_arm[0], ball_arm[2] - base_arm[2]],
        dtype=float,
    )
    norm = float(np.linalg.norm(dir_xz))
    if norm < 1e-6:
        return np.array([0.0, -1.0], dtype=float)
    return dir_xz / norm


def target_section3_bend_delta_for_ball(
    ball_center_mm: np.ndarray,
    robot_base_mm: np.ndarray,
    approach: str = "side",
    vision_to_arm_scale: np.ndarray | None = None,
) -> np.ndarray:
    """Section-3 bend in XZ toward ball (inverted arm frame)."""
    dir_xz = _ball_dir_yz_arm(ball_center_mm, robot_base_mm, approach, vision_to_arm_scale)
    m1, m4 = maximize_motor14_for_bend_direction(dir_xz)
    return motor14_steps_to_bend_delta(m1, m4)


def section3_pose_from_grasp_motor14(
    home_pose: np.ndarray,
    motor1_steps: int,
    motor4_steps: int,
    steps_per_degree: float = DEFAULT_REF_STEPS_PER_DEGREE,
) -> np.ndarray:
    home_pose = np.asarray(home_pose, dtype=float)
    delta = motor14_steps_to_bend_delta(motor1_steps, motor4_steps, steps_per_degree)
    return apply_section3_bend_xy(home_pose, section3_bend_xy(home_pose) + delta)


def plane_phi_from_xz_mm(
    x_mm: float,
    z_mm: float,
    phi_offset_deg: float = SECTION12_PHI_OFFSET_DEG,
) -> float:
    """Plane angle for inverted arm: phi=atan2(Z, X)+offset in XZ bend plane."""
    phi_deg = float(np.degrees(np.arctan2(float(z_mm), float(x_mm)))) + float(phi_offset_deg)
    return phi_deg % 360.0


def section12_bend_xz(pose: np.ndarray, section: int) -> np.ndarray:
    if section == 1:
        return _planned_bend_xz(pose, 0, 3)
    if section == 2:
        return _planned_bend_xz(pose, 1, 4)
    raise ValueError("section must be 1 or 2")


def apply_section12_bend_xz(pose: np.ndarray, section: int, bend_xz: np.ndarray) -> np.ndarray:
    """Write section 1 or 2 bend vector into pose Plane/Theta indices."""
    out = np.asarray(pose, dtype=float).copy()
    phi_deg, theta_deg = bend_xy_to_plane_theta_deg(np.asarray(bend_xz, dtype=float))
    if section == 1:
        out[0], out[3] = phi_deg, theta_deg
    elif section == 2:
        out[1], out[4] = phi_deg, theta_deg
    else:
        raise ValueError("section must be 1 or 2")
    return out


def solve_sections_12_inverse_kinematics(
    rope_home: np.ndarray,
    ball_center_mm: np.ndarray,
    base_mm: np.ndarray | None = None,
    *,
    phi_offset_deg: float = SECTION12_PHI_OFFSET_DEG,
    vision_to_arm_scale: np.ndarray | None = None,
) -> np.ndarray:
    """
    第 1–2 节逆运动学：倒立软体臂在 XZ 弯曲平面内朝球。

    ``ball_center_mm`` 为 soft_arm_center 下球心 [x,y,z] mm。
    """
    rope_home = np.asarray(rope_home, dtype=float)
    ball_center_mm = np.asarray(ball_center_mm, dtype=float).reshape(3)
    ball_arm = vision_center_to_arm_mm(ball_center_mm, vision_to_arm_scale)
    if base_mm is None:
        base_arm = DEFAULT_ARM_BASE_MM.copy()
    else:
        base_arm = vision_center_to_arm_mm(
            np.asarray(base_mm, dtype=float).reshape(3), vision_to_arm_scale
        )

    to_ball_xz = np.array(
        [ball_arm[0] - base_arm[0], ball_arm[2] - base_arm[2]],
        dtype=float,
    )
    dist = float(np.linalg.norm(to_ball_xz))
    if dist < 1e-6:
        x_mm, z_mm = 0.0, -1.0
    else:
        x_mm, z_mm = float(to_ball_xz[0]), float(to_ball_xz[1])

    phi_deg = plane_phi_from_xz_mm(x_mm, z_mm, phi_offset_deg)
    u_ball = np.array([x_mm, z_mm], dtype=float)
    norm = float(np.linalg.norm(u_ball))
    if norm > 1e-6:
        u_ball = u_ball / norm
    else:
        u_ball = np.array([0.0, -1.0], dtype=float)

    bend_scale = min(28.0, 8.0 + dist * 0.035)
    cap = MAX_SECTION12_POSE_DELTA

    pose = rope_home.copy()
    for section, weight, phi_idx, theta_idx in (
        (1, 0.55, 0, 3),
        (2, 0.45, 1, 4),
    ):
        bend_home = section12_bend_xz(rope_home, section)
        add_mag = float(np.clip(bend_scale * weight, 0.0, cap[theta_idx]))
        bend_target = bend_home + add_mag * u_ball
        # 朝 +X 球时保证 X 分量不减（避免 Plane 从 34° 收到 0° 导致 motor6 负步进）
        if u_ball[0] > 0.5 and bend_target[0] < bend_home[0]:
            bend_target[0] = bend_home[0] + add_mag * u_ball[0]
        if u_ball[0] < -0.5 and bend_target[0] > bend_home[0]:
            bend_target[0] = bend_home[0] + add_mag * u_ball[0]
        pose = apply_section12_bend_xz(pose, section, bend_target)
    return pose


def solve_section3_y_symmetric_motor14(
    home_pose: np.ndarray,
    ball_kinematic_mm: np.ndarray,
) -> tuple[int, int, np.ndarray]:
    """
    Section-3 grasp with fixed J-shape closure, mirrored across Y for ball +/-X.

    Uses motor1_4_test template: ball on -X -> m1 negative (+X bend); on +X -> m1 positive.
    """
    home_pose = np.asarray(home_pose, dtype=float)
    ball_kinematic_mm = np.asarray(ball_kinematic_mm, dtype=float)
    m1_mag = abs(int(REF_GRASP_MOTOR1_STEPS))
    m4 = int(REF_GRASP_MOTOR4_STEPS)
    bx = float(ball_kinematic_mm[0])
    # motor1+ -> -X；朝 +X 弯需 m1<0，朝 -X 弯需 m1>0
    m1 = m1_mag if bx <= 0.0 else -m1_mag
    m1, m4 = project_motor14_to_grasp_range(m1, m4)
    pose = section3_pose_from_grasp_motor14(home_pose, m1, m4)
    return m1, m4, pose


def solve_section3_grasp_motor14(
    home_pose: np.ndarray,
    ball_center_mm: np.ndarray,
    robot_base_mm: np.ndarray,
    approach: str = "side",
    vision_to_arm_scale: np.ndarray | None = None,
) -> tuple[int, int, np.ndarray]:
    """Kinematic grasp: bend toward ball with motor1/4 in the feasible envelope.

    ``home_pose`` should be the rope zero pose (section-3 angles cleared), matching
    the reference used for relative motor step commands on the bus.
    """
    home_pose = np.asarray(home_pose, dtype=float)
    delta = target_section3_bend_delta_for_ball(
        ball_center_mm, robot_base_mm, approach, vision_to_arm_scale
    )
    m1, m4 = bend_delta_to_motor14_steps(delta)
    m1, m4 = project_motor14_to_grasp_range(m1, m4)
    pose = section3_pose_from_grasp_motor14(home_pose, m1, m4)
    return m1, m4, pose


def bend_xy_to_plane_theta_deg(bend_xy: np.ndarray) -> tuple[float, float]:
    bend_xy = np.asarray(bend_xy, dtype=float)
    theta_deg = float(np.linalg.norm(bend_xy))
    phi_deg = float(np.degrees(np.arctan2(bend_xy[1], bend_xy[0])))
    if phi_deg < 0.0:
        phi_deg += 360.0
    return phi_deg, theta_deg


def apply_section3_bend_xy(pose: np.ndarray, bend_xy: np.ndarray) -> np.ndarray:
    out = np.asarray(pose, dtype=float).copy()
    out[SECTION3_PHI_IDX], out[SECTION3_THETA_IDX] = bend_xy_to_plane_theta_deg(bend_xy)
    return out


def reference_section3_pose_from_home(home_pose: np.ndarray) -> np.ndarray:
    """Pose whose section-3 bend matches the default feasible motor1/4 grasp."""
    return section3_pose_from_grasp_motor14(
        home_pose, REF_GRASP_MOTOR1_STEPS, REF_GRASP_MOTOR4_STEPS
    )


def pose_pair_to_motor_steps(
    before_pose: np.ndarray,
    after_pose: np.ndarray,
    steps_per_degree: list[float],
    min_step_delta: int = DEFAULT_MIN_STEP_DELTA,
) -> list[int]:
    """Convert one GP waypoint pair to six motor step deltas."""
    before_pose = np.asarray(before_pose, dtype=float)
    after_pose = np.asarray(after_pose, dtype=float)
    vec = [0, 0, 0, 0, 0, 0]

    for phi_idx, theta_idx, motor_a, motor_b, phi_a, phi_b in SECTION_ROPE_PAIRS:
        delta_bend = _planned_bend_xy(after_pose, phi_idx, theta_idx) - _planned_bend_xy(
            before_pose, phi_idx, theta_idx
        )
        dtheta_a, dtheta_b = _decompose_bend_xy_to_rope_thetas(delta_bend, phi_a, phi_b)
        for motor_id, dtheta in ((motor_a, dtheta_a), (motor_b, dtheta_b)):
            idx = motor_id - 1
            vec[idx] += _theta_delta_to_step(
                dtheta, steps_per_degree[idx], min_step_delta
            )
    return vec


def _checksum(data: list[int]) -> int:
    return (~sum(data)) & 0xFF


def build_enable_torque(servo_id: int, enable: int = 1) -> bytes:
    body = [servo_id, 0x04, 0x03, 0x28, enable & 0xFF]
    body.append(_checksum(body))
    return HEADER + bytes(body)


def build_write_step_delta(
    servo_id: int, delta_steps: int, time_ms: int = 0, speed: int = DEFAULT_SPEED
) -> bytes:
    d = int(round(delta_steps))
    if d == 0:
        raise ValueError("delta_steps cannot be 0")
    d = max(-32767, min(32767, d))
    if d > 0:
        u = d & 0x7FFF
    else:
        u = 0x8000 | ((-d) & 0x7FFF)
    pos_l = u & 0xFF
    pos_h = (u >> 8) & 0xFF
    time_h = (time_ms >> 8) & 0xFF
    time_l = time_ms & 0xFF
    spd_h = (speed >> 8) & 0xFF
    spd_l = speed & 0xFF
    body = [servo_id, 9, 0x03, 0x2A, pos_l, pos_h, time_h, time_l, spd_h, spd_l]
    body.append(_checksum(body))
    return HEADER + bytes(body)


class FeetechBus:
    def __init__(self, port: str, baud: int = 1000000, debug: bool = False):
        self.ser = serial.Serial(port, baud, timeout=0.15)
        self.lock = threading.Lock()
        self.debug = debug

    def _write_byte_by_byte(self, data: bytes):
        with self.lock:
            for b in data:
                self.ser.write(bytes([b]))
            self.ser.flush()
            if self.debug:
                print(f"    TX: {data.hex(' ')}")
            time.sleep(0.003)

    def enable_torque(self, servo_id: int, enable: int = 1):
        self._write_byte_by_byte(build_enable_torque(servo_id, enable))

    def write_step_delta(
        self, servo_id: int, delta_steps: int, time_ms: int = 0, speed: int = DEFAULT_SPEED
    ):
        self._write_byte_by_byte(
            build_write_step_delta(servo_id, delta_steps, time_ms, speed)
        )

    def close(self):
        self.ser.close()


def step_delta_to_time_ms(
    delta: int,
    ms_per_step: float = 2.0,
    min_ms: int = 300,
    max_ms: int = 8000,
) -> int:
    """Feetech 需要非零 time_ms 才会按步进运动；按步数估算动作时间。"""
    return int(max(min_ms, min(max_ms, abs(int(delta)) * float(ms_per_step))))


def send_vec(
    bus: FeetechBus,
    vec: list[int],
    speed: int,
    *,
    simple: bool = False,
    verbose: bool = False,
    ms_per_step: float = 2.0,
    wait_after: bool = True,
) -> float:
    """
    Send relative step deltas.

    simple=True: 与 motor1_4_test.py 相同（time_ms=0，不在此处等待，靠外部 hold）。
    """
    max_wait_s = 0.0
    sent = 0
    for i, delta in enumerate(vec, start=1):
        d = int(delta)
        if d == 0:
            continue
        if simple:
            t_ms = 0
        else:
            t_ms = step_delta_to_time_ms(d, ms_per_step=ms_per_step)
        if verbose:
            print(f"  [TX] motor{i}: delta={d:+d} time_ms={t_ms} speed={speed}")
        bus.write_step_delta(i, d, t_ms, speed)
        if not simple:
            max_wait_s = max(max_wait_s, t_ms / 1000.0)
        sent += 1
    if wait_after and sent > 0 and not simple:
        pause_s = max_wait_s + 0.15
        if verbose:
            print(f"  [TX] wait {pause_s:.2f}s for move(s) to finish")
        time.sleep(pause_s)
        return pause_s
    return 0.0


# 第 1–2 节电机索引 (0-based): motor2,3,5,6
_SECTION12_MOTOR_IDX = (1, 2, 4, 5)
_GRASP_BLEND_START_DEFAULT = 0.45


def execute_kinematic_plan_v2(
    bus: FeetechBus,
    plan: dict,
    speed: int,
    steps_per_degree: list[float],
    *,
    waypoint_stride: int = 3,
    min_step_delta: int = DEFAULT_MIN_STEP_DELTA,
    max_abs_steps: list[int] | None = None,
    start_delay_s: float = 5.0,
    hold_grasp_s: float = 10.0,
    hold_approach_s: float = 2.0,
    return_home: bool = True,
    verbose: bool = False,
    grasp_blend_start: float = _GRASP_BLEND_START_DEFAULT,
) -> list[int]:
    """
    按 grasp_plan_v2 轨迹执行绳组运动学规划:
      1) 第 1–2 节接近 (motor2/3/5/6，Plane/Theta 朝球)
      2) 第 3 节抓取 (motor1/4，与 motor1_4_test 相同发送方式)
    """
    if max_abs_steps is None:
        max_abs_steps = [8000, 4000, 4000, 8000, 4000, 4000]

    trajectory = plan["trajectory_deg"]
    metrics = plan.get("metrics", {})
    m1 = int(metrics.get("motor1_steps_cmd", metrics.get("motor1_steps", 0)))
    m4 = int(metrics.get("motor4_steps_cmd", metrics.get("motor4_steps", 0)))
    if m1 == 0 and m4 == 0:
        raise ValueError("plan 缺少 motor1_steps_cmd / motor4_steps_cmd，请先运行 v2 规划")

    vectors = trajectory_to_step_vectors(
        trajectory,
        steps_per_degree,
        waypoint_stride=waypoint_stride,
        min_step_delta=min_step_delta,
    )
    n_seg = max(len(vectors), 1)
    approach_acc = [0, 0, 0, 0, 0, 0]
    for i, vec in enumerate(vectors):
        phase = (i + 1) / n_seg
        if phase < grasp_blend_start:
            for midx in _SECTION12_MOTOR_IDX:
                approach_acc[midx] += int(vec[midx])

    home_pose = np.asarray(trajectory[0], dtype=float)
    final_pose = np.asarray(plan["final_pose_deg"], dtype=float)
    print(
        "[Kinematic] 规划轨迹: "
        f"waypoints={len(trajectory)}  segments={len(vectors)}  blend@{grasp_blend_start:.0%}"
    )
    print(
        f"  第1–2节目标: Plane1={final_pose[0]:.1f}° Plane2={final_pose[1]:.1f}° "
        f"Theta1={final_pose[3]:.1f}° Theta2={final_pose[4]:.1f}°"
    )
    print(f"  第1–2节步进累计 motor2/3/5/6 = {[approach_acc[i] for i in _SECTION12_MOTOR_IDX]}")
    print(f"  第3节步进 motor1={m1} motor4={m4}")

    current_steps = [0, 0, 0, 0, 0, 0]
    if start_delay_s > 0:
        print(f"--- Start delay {start_delay_s:.1f}s ---")
        time.sleep(start_delay_s)

    if any(approach_acc[i] for i in _SECTION12_MOTOR_IDX):
        print(f"--- 第1–2节接近: {approach_acc} ---")
        current_steps = send_protected_vec(
            bus,
            approach_acc,
            speed,
            current_steps,
            max_abs_steps,
            simple=True,
            verbose=verbose,
            wait_after=False,
        )
        print(f"--- 接近保持 {hold_approach_s:.1f}s ---")
        time.sleep(hold_approach_s)
    else:
        print("--- 第1–2节接近步进为 0，跳过 ---")

    m1, m4 = project_motor14_to_grasp_range(m1, m4)
    move_vec = [m1, 0, 0, m4, 0, 0]
    print(f"--- 第3节抓取: {move_vec} ---")
    current_steps = send_protected_vec(
        bus,
        move_vec,
        speed,
        current_steps,
        max_abs_steps,
        simple=True,
        verbose=verbose,
        wait_after=False,
    )
    print(f"--- 抓取保持 {hold_grasp_s:.1f}s ---")
    time.sleep(hold_grasp_s)

    if return_home:
        home_vec = [-x for x in current_steps]
        print(f"--- 全程复位: {home_vec} ---")
        send_vec(
            bus,
            home_vec,
            speed,
            simple=True,
            verbose=verbose,
            wait_after=False,
        )
        return [0, 0, 0, 0, 0, 0]
    return current_steps


def execute_motor14_grasp(
    bus: FeetechBus,
    motor1_steps: int,
    motor4_steps: int,
    speed: int = DEFAULT_SPEED,
    *,
    start_delay_s: float = 5.0,
    hold_s: float = 10.0,
    return_home: bool = True,
    verbose: bool = False,
) -> list[int]:
    """
    与 motor1_4_test.py 相同：只驱动第三节 motor1 + motor4，hold 后可选复位。
    返回本次累计步进 [m1..m6]。
    """
    m1, m4 = project_motor14_to_grasp_range(int(motor1_steps), int(motor4_steps))
    move_vec = [m1, 0, 0, m4, 0, 0]
    home_vec = [-m1, 0, 0, -m4, 0, 0]
    print(f"[Grasp] move vec={move_vec}  (|m1|+|m4|={abs(m1)+abs(m4)})")
    if start_delay_s > 0:
        print(f"--- Start delay {start_delay_s:.1f}s ---")
        time.sleep(start_delay_s)
    send_vec(bus, move_vec, speed, simple=True, verbose=verbose, wait_after=False)
    print(f"--- Hold {hold_s:.1f}s ---")
    time.sleep(hold_s)
    if return_home:
        print(f"--- Return home: {home_vec} ---")
        send_vec(bus, home_vec, speed, simple=True, verbose=verbose, wait_after=False)
        return [0, 0, 0, 0, 0, 0]
    return move_vec


def add_vec(a: list[int], b: list[int]) -> list[int]:
    return [int(x) + int(y) for x, y in zip(a, b)]


def clamp_vec_to_step_limits(
    vec: list[int],
    current_steps: list[int],
    max_abs_steps: list[int],
) -> list[int]:
    """Clamp a relative command so cumulative motor position stays in limits."""
    out: list[int] = []
    for idx, (delta, current, limit) in enumerate(zip(vec, current_steps, max_abs_steps), start=1):
        desired = int(current) + int(delta)
        clipped = max(-int(limit), min(int(limit), desired))
        safe_delta = clipped - int(current)
        if safe_delta != int(delta):
            print(
                f"[Protect] motor{idx}: requested cumulative {desired}, "
                f"clipped to {clipped} (limit +/-{int(limit)})"
            )
        out.append(safe_delta)
    return out


def send_protected_vec(
    bus: FeetechBus,
    vec: list[int],
    speed: int,
    current_steps: list[int],
    max_abs_steps: list[int],
    *,
    simple: bool = False,
    verbose: bool = False,
    ms_per_step: float = 2.0,
    wait_after: bool = True,
) -> list[int]:
    safe_vec = clamp_vec_to_step_limits(vec, current_steps, max_abs_steps)
    if verbose and safe_vec != vec:
        print(f"  [Protect] clipped {vec} -> {safe_vec}")
    send_vec(
        bus,
        safe_vec,
        speed,
        simple=simple,
        verbose=verbose,
        ms_per_step=ms_per_step,
        wait_after=wait_after,
    )
    return add_vec(current_steps, safe_vec)


def parse_float_list(raw: str, expected: int, name: str) -> list[float]:
    values = [float(x.strip()) for x in raw.split(",") if x.strip()]
    if len(values) == 1:
        values = values * expected
    if len(values) != expected:
        raise argparse.ArgumentTypeError(f"{name} must contain 1 or {expected} comma-separated values")
    return values


def load_plan(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        plan = json.load(f)
    trajectory = plan.get("trajectory_deg")
    if not trajectory or len(trajectory) < 2:
        raise ValueError("plan must contain trajectory_deg with at least two waypoints")
    for row in trajectory:
        if len(row) != 6:
            raise ValueError("each trajectory_deg waypoint must contain 6 angles")
    return plan


def trajectory_to_step_vectors(
    trajectory_deg: list[list[float]],
    steps_per_degree: list[float],
    waypoint_stride: int = 1,
    min_step_delta: int = DEFAULT_MIN_STEP_DELTA,
) -> list[list[int]]:
    if waypoint_stride < 1:
        raise ValueError("waypoint_stride must be >= 1")

    selected = trajectory_deg[::waypoint_stride]
    if selected[-1] != trajectory_deg[-1]:
        selected.append(trajectory_deg[-1])

    step_vectors: list[list[int]] = []
    previous = selected[0]
    for waypoint in selected[1:]:
        vec = pose_pair_to_motor_steps(previous, waypoint, steps_per_degree, min_step_delta)
        if any(vec):
            step_vectors.append(vec)
        previous = waypoint
    return step_vectors


def apply_live_vision_adjust(
    bus: FeetechBus,
    current_pose: np.ndarray,
    ball_center_mm: np.ndarray,
    plan: dict,
    speed: int,
    steps_per_degree: list[float],
    min_step_delta: int,
    current_steps: list[int],
    max_abs_steps: list[int],
    max_angle_deg: float = DEFAULT_SERVO_MAX_ANGLE_DEG,
    success_gap_mm: float = DEFAULT_SERVO_SUCCESS_GAP_MM,
) -> tuple[np.ndarray, list[int], bool]:
    """One-shot section-3 correction from a live D435 observation."""
    radius = float(plan.get("ball_radius_mm", 35.0))
    pose = np.asarray(current_pose, dtype=float)
    gap = _distal_surface_gap(pose, ball_center_mm, radius)
    if gap <= success_gap_mm:
        return pose, current_steps, False

    next_pose, info = optimize_third_section_compensation(
        pose, ball_center_mm, radius, max_angle_deg=max_angle_deg
    )
    vec = pose_delta_to_step_vec(pose, next_pose, steps_per_degree, min_step_delta)
    vec = [vec[0], 0, 0, vec[3], 0, 0]
    safe_vec = clamp_vec_to_step_limits(vec, current_steps, max_abs_steps)
    if not any(safe_vec):
        return pose, current_steps, False

    print(
        f"[D435] live adjust gap={gap:.1f}mm -> {info['min_gap_mm']:.1f}mm, "
        f"motor14 steps={safe_vec[0]}, {safe_vec[3]}"
    )
    send_vec(bus, safe_vec, speed)
    time.sleep(0.12)
    return next_pose, add_vec(current_steps, safe_vec), True


def execute_plan(
    bus: FeetechBus,
    plan: dict,
    speed: int,
    steps_per_degree: list[float],
    waypoint_stride: int,
    waypoint_delay_s: float,
    min_step_delta: int,
    return_home: bool,
    max_abs_steps: list[int],
    vision_tracker=None,
    vision_adjust_every: int = 2,
    vision_max_angle_deg: float = DEFAULT_SERVO_MAX_ANGLE_DEG,
    max_grasp_s: float | None = None,
    verbose: bool = False,
    ms_per_step: float = 2.0,
) -> list[int]:
    step_vectors = trajectory_to_step_vectors(
        plan["trajectory_deg"],
        steps_per_degree,
        waypoint_stride=waypoint_stride,
        min_step_delta=min_step_delta,
    )
    trajectory = plan["trajectory_deg"]
    selected_idx = list(range(0, len(trajectory), max(1, waypoint_stride)))
    if selected_idx[-1] != len(trajectory) - 1:
        selected_idx.append(len(trajectory) - 1)

    current_steps = [0, 0, 0, 0, 0, 0]
    requested_total = [sum(vec[i] for vec in step_vectors) for i in range(6)]
    current_pose = np.asarray(trajectory[0], dtype=float)

    print(
        f"[Plan] approach={plan.get('approach')}, success={plan.get('success')}, "
        f"waypoints={len(step_vectors)}, requested_total_steps={requested_total}"
    )
    if vision_tracker is not None:
        print(f"[D435] live vision enabled: adjust every {max(1, vision_adjust_every)} waypoint(s)")
    grasp_start = time.time()
    if max_grasp_s is not None:
        print(f"[Grasp] max curl/grasp time {max_grasp_s:.1f}s")

    for idx, vec in enumerate(step_vectors, start=1):
        if max_grasp_s is not None and time.time() - grasp_start >= max_grasp_s:
            print(f"[Grasp] reached {max_grasp_s:.1f}s limit; stop trajectory early.")
            break
        print(f"--- Waypoint {idx}/{len(step_vectors)}: {vec} ---")
        current_steps = send_protected_vec(
            bus,
            vec,
            speed,
            current_steps,
            max_abs_steps,
            verbose=verbose,
            ms_per_step=ms_per_step,
            wait_after=True,
        )
        traj_i = selected_idx[min(idx, len(selected_idx) - 1)]
        current_pose = np.asarray(trajectory[traj_i], dtype=float)

        if vision_tracker is not None and idx % max(1, vision_adjust_every) == 0:
            obs = vision_tracker.get_latest()
            if obs.valid and obs.center_mm is not None:
                current_pose, current_steps, _ = apply_live_vision_adjust(
                    bus,
                    current_pose,
                    obs.center_mm,
                    plan,
                    speed,
                    steps_per_degree,
                    min_step_delta,
                    current_steps,
                    max_abs_steps,
                    max_angle_deg=vision_max_angle_deg,
                )
            else:
                print(
                    f"[D435] skip adjust at waypoint {idx}: "
                    f"{obs.reason or obs.tag_status}"
                )
        if waypoint_delay_s > 0:
            time.sleep(waypoint_delay_s)

    if return_home:
        home_vec = [-x for x in current_steps]
        print(f"--- Return home vec: {home_vec} ---")
        send_vec(
            bus,
            home_vec,
            speed,
            verbose=verbose,
            ms_per_step=ms_per_step,
            wait_after=True,
        )
        current_steps = [0, 0, 0, 0, 0, 0]
    return current_steps


def _import_planning_tools():
    import GP_tennis as gp
    from grasp_planning import (
        _surface_gap,
        detect_tennis_ball_realsense,
        load_camera_to_robot,
    )

    return gp, _surface_gap, detect_tennis_ball_realsense, load_camera_to_robot


def _distal_surface_gap(pose_deg: np.ndarray, ball_center: np.ndarray, radius: float) -> float:
    gp, surface_gap, _, _ = _import_planning_tools()
    points = gp.pose_to_points(pose_deg, gp.SEGMENT_LENGTHS, gp.ROBOT_BASE)
    distal = points[34:]
    return float(np.min(surface_gap(distal, ball_center, radius)))


def optimize_third_section_compensation(
    pose_deg: np.ndarray,
    ball_center: np.ndarray,
    radius: float,
    max_angle_deg: float,
) -> tuple[np.ndarray, dict]:
    """Tune only section-3 plane/bending angles so the distal arm wraps the ball."""
    gp, surface_gap, _, _ = _import_planning_tools()
    base_pose = np.asarray(pose_deg, dtype=float)
    best_pose = base_pose.copy()
    lower = base_pose.copy()
    upper = base_pose.copy()
    for dim in (2, 5):
        lower[dim] = max(0.0, base_pose[dim] - max_angle_deg)
        upper[dim] = min(170.0 if dim == 5 else 360.0, base_pose[dim] + max_angle_deg)

    def evaluate(candidate: np.ndarray) -> tuple[float, dict]:
        candidate = candidate.copy()
        candidate[2] = np.clip(candidate[2], lower[2], upper[2])
        candidate[5] = np.clip(candidate[5], lower[5], upper[5])
        points = gp.pose_to_points(candidate, gp.SEGMENT_LENGTHS, gp.ROBOT_BASE)
        distal = points[34:]
        gaps = surface_gap(distal, ball_center, radius)
        min_gap = float(np.min(gaps))
        tip_gap = float(surface_gap(points[-1], ball_center, radius)[0])
        near_count = int(np.sum(gaps <= max(10.0, radius * 0.35)))
        delta = candidate - base_pose
        regularization = 0.25 * float(np.linalg.norm(delta[[2, 5]]))
        score = min_gap + 0.30 * tip_gap - 1.5 * min(near_count, 6) + regularization
        return score, {
            "min_gap_mm": min_gap,
            "tip_gap_mm": tip_gap,
            "near_count": near_count,
            "pose_deg": candidate,
        }

    best_score, best_info = evaluate(best_pose)
    for step in (4.0, 2.0, 1.0, 0.5):
        improved = True
        while improved:
            improved = False
            for dim in (2, 5):
                for direction in (-1.0, 1.0):
                    candidate = best_pose.copy()
                    candidate[dim] += direction * step
                    score, info = evaluate(candidate)
                    if score + 1e-6 < best_score:
                        best_pose = info["pose_deg"]
                        best_score = score
                        best_info = info
                        improved = True
    best_info["delta_deg"] = best_pose - base_pose
    return best_pose, best_info


def pose_delta_to_step_vec(
    before_pose: np.ndarray,
    after_pose: np.ndarray,
    steps_per_degree: list[float],
    min_step_delta: int,
) -> list[int]:
    return pose_pair_to_motor_steps(before_pose, after_pose, steps_per_degree, min_step_delta)


def run_visual_servo_compensation(
    bus: FeetechBus | None,
    current_pose: list[float],
    plan: dict,
    speed: int,
    steps_per_degree: list[float],
    vision_config_path: Path | None,
    max_iters: int,
    success_gap_mm: float,
    max_angle_deg: float,
    min_step_delta: int,
    current_steps: list[int],
    max_abs_steps: list[int],
    dry_run: bool,
    vision_tracker=None,
) -> tuple[list[float], list[int]]:
    radius = float(plan.get("ball_radius_mm", 33.0))
    pose = np.asarray(current_pose, dtype=float)
    total_comp = [0, 0, 0, 0, 0, 0]

    def _ball_center_mm():
        if vision_tracker is not None:
            obs = vision_tracker.get_latest()
            if obs.valid and obs.center_mm is not None:
                return obs.center_mm
            return None
        gp, _, _, _ = _import_planning_tools()
        from vision_catch_ball import detect_tennis_once, load_vision_config

        vision_cfg = load_vision_config(vision_config_path)
        det = detect_tennis_once(vision_cfg=vision_cfg, no_viz=True)
        return det.ball_center_mm

    for idx in range(1, max_iters + 1):
        ball_center = _ball_center_mm()
        if ball_center is None:
            print(f"[VisualServo] iter={idx}, no valid D435 observation; stop.")
            break
        gap = _distal_surface_gap(pose, ball_center, radius)
        print(f"[VisualServo] iter={idx}, distal_surface_gap={gap:.1f} mm")
        if gap <= success_gap_mm:
            print("[VisualServo] third section is close enough to the tennis ball.")
            break

        next_pose, info = optimize_third_section_compensation(
            pose,
            ball_center,
            radius,
            max_angle_deg=max_angle_deg,
        )
        vec = pose_delta_to_step_vec(pose, next_pose, steps_per_degree, min_step_delta)
        # Third section only: motor1 (phi180) and motor4 (phi270) rope pair.
        vec = [vec[0], 0, 0, vec[3], 0, 0]
        safe_vec = clamp_vec_to_step_limits(vec, current_steps, max_abs_steps)
        if not any(vec):
            print("[VisualServo] compensation is below min-step threshold; stop.")
            break
        if not any(safe_vec):
            print("[VisualServo] compensation reached protection limit; stop.")
            break

        print(
            f"[VisualServo] send third-section compensation={safe_vec}, "
            f"predicted_gap={info['min_gap_mm']:.1f} mm"
        )
        if not dry_run and bus is not None:
            send_vec(bus, safe_vec, speed)
            time.sleep(0.25)
        pose = next_pose
        current_steps = add_vec(current_steps, safe_vec)
        total_comp = add_vec(total_comp, safe_vec)

    return pose.tolist(), total_comp


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Execute fixed J-shape or a grasp_plan.json trajectory"
    )
    p.add_argument("--port", default="COM5")
    p.add_argument("--baud", type=int, default=1000000)
    p.add_argument("--speed", type=int, default=DEFAULT_SPEED)
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--debug", action="store_true")
    p.add_argument("--plan", type=Path, help="JSON plan from grasp_planning.py")
    p.add_argument(
        "--steps-per-degree",
        default="100",
        help="1 or 6 comma-separated motor step/degree calibration values",
    )
    p.add_argument("--waypoint-stride", type=int, default=3)
    p.add_argument("--waypoint-delay", type=float, default=DEFAULT_WAYPOINT_DELAY_S)
    p.add_argument("--min-step-delta", type=int, default=DEFAULT_MIN_STEP_DELTA)
    p.add_argument("--no-return-home", action="store_true")
    p.add_argument(
        "--grasp-hold",
        type=float,
        default=DEFAULT_GRASP_HOLD_S,
        help="hold the curled grasp before restoring position",
    )
    p.add_argument(
        "--step-limits",
        default="8000,4000,4000,8000,4000,4000",
        help="absolute cumulative step limits for motors 1..6",
    )
    p.add_argument(
        "--visual-servo",
        action="store_true",
        help="after plan execution, use D435 visual feedback to compensate section 3 before returning home",
    )
    p.add_argument("--camera-to-robot", type=Path, help="legacy JSON 4x4 camera_to_robot transform")
    p.add_argument(
        "--vision-calib",
        type=Path,
        help="legacy JSON with base_origin_camera_mm and metal_rod_z_camera_mm",
    )
    p.add_argument(
        "--vision-config",
        type=Path,
        default=Path(__file__).resolve().parent / "config" / "vision_local.json",
        help="catch_ball HSV+AprilTag config for visual servo",
    )
    p.add_argument("--servo-max-iters", type=int, default=DEFAULT_SERVO_MAX_ITERS)
    p.add_argument("--servo-success-gap", type=float, default=DEFAULT_SERVO_SUCCESS_GAP_MM)
    p.add_argument("--servo-max-angle", type=float, default=DEFAULT_SERVO_MAX_ANGLE_DEG)
    return p.parse_args()


def main() -> None:
    args = parse_args()
    steps_per_degree = parse_float_list(args.steps_per_degree, 6, "steps_per_degree")
    step_limits = [int(v) for v in parse_float_list(args.step_limits, 6, "step_limits")]

    plan = load_plan(args.plan) if args.plan else None
    if plan is not None:
        print(f"[Plan] loaded {args.plan}")
        print(f"[Plan] steps_per_degree={steps_per_degree}")
        print(f"[Protect] step_limits={step_limits}")
        if plan.get("success") is False:
            print("[Warning] planner marked this grasp as not meeting success thresholds.")
        if args.dry_run:
            vectors = trajectory_to_step_vectors(
                plan["trajectory_deg"],
                steps_per_degree,
                waypoint_stride=args.waypoint_stride,
                min_step_delta=args.min_step_delta,
            )
            safe_vectors = []
            dry_current = [0, 0, 0, 0, 0, 0]
            for vec in vectors:
                safe_vec = clamp_vec_to_step_limits(vec, dry_current, step_limits)
                dry_current = add_vec(dry_current, safe_vec)
                safe_vectors.append(safe_vec)
            print(f"--dry-run enabled: no serial command sent. step_vectors={vectors}")
            print(f"--dry-run protected vectors={safe_vectors}, final_steps={dry_current}")
            if args.visual_servo:
                print("--visual-servo is skipped in dry-run mode.")
            return

        try:
            bus = FeetechBus(args.port, args.baud, debug=args.debug)
        except (serial.SerialException, PermissionError, OSError) as e:
            print(f"Failed to open serial port {args.port}: {e}")
            sys.exit(1)

        try:
            for sid in range(1, 7):
                bus.enable_torque(sid, 1)
                time.sleep(0.03)
            time.sleep(0.08)

            print(f"\n--- Start delay {START_DELAY_S:.1f}s before execution ---")
            time.sleep(START_DELAY_S)
            total_vec = execute_plan(
                bus,
                plan,
                args.speed,
                steps_per_degree,
                args.waypoint_stride,
                args.waypoint_delay,
                args.min_step_delta,
                return_home=False,
                max_abs_steps=step_limits,
            )
            if args.visual_servo:
                _, comp_vec = run_visual_servo_compensation(
                    bus,
                    plan["trajectory_deg"][-1],
                    plan,
                    args.speed,
                    steps_per_degree,
                    args.vision_config,
                    args.servo_max_iters,
                    args.servo_success_gap,
                    args.servo_max_angle,
                    args.min_step_delta,
                    total_vec,
                    step_limits,
                    dry_run=False,
                )
                total_vec = add_vec(total_vec, comp_vec)

            if not args.no_return_home:
                if args.grasp_hold > 0:
                    print(f"--- Hold curled grasp {args.grasp_hold:.1f}s before restore ---")
                    time.sleep(args.grasp_hold)
                home_vec = [-x for x in total_vec]
                print(f"--- Return home vec: {home_vec} ---")
                send_vec(bus, home_vec, args.speed)
            print("\nDone.")
        except KeyboardInterrupt:
            print("\nInterrupted by user.")
        finally:
            bus.close()
        return

    current_steps = [0, 0, 0, 0, 0, 0]
    safe_vec_1 = clamp_vec_to_step_limits(JSHAPE_VEC_1, current_steps, step_limits)
    current_after_vec1 = add_vec(current_steps, safe_vec_1)
    safe_vec_2 = clamp_vec_to_step_limits(JSHAPE_VEC_2, current_after_vec1, step_limits)
    total_vec = add_vec(current_after_vec1, safe_vec_2)
    home_vec = [-x for x in total_vec]
    print(
        f"[Plan] soft J-shape: {safe_vec_1} -> hold {HOLD_AFTER_VEC1_S:.1f}s "
        f"-> {safe_vec_2} -> hold {HOLD_BEFORE_HOME_S:.1f}s -> {home_vec}(home)"
    )

    if args.dry_run:
        print("--dry-run enabled: no serial command sent.")
        return

    try:
        bus = FeetechBus(args.port, args.baud, debug=args.debug)
    except (serial.SerialException, PermissionError, OSError) as e:
        print(f"Failed to open serial port {args.port}: {e}")
        sys.exit(1)

    try:
        for sid in range(1, 7):
            bus.enable_torque(sid, 1)
            time.sleep(0.03)
        time.sleep(0.08)

        print(f"\n--- Start delay {START_DELAY_S:.1f}s before execution ---")
        time.sleep(START_DELAY_S)

        print(f"\n--- Execute vec1: {JSHAPE_VEC_1} ---")
        current_steps = send_protected_vec(bus, JSHAPE_VEC_1, args.speed, current_steps, step_limits)

        print(f"\n--- Hold {HOLD_AFTER_VEC1_S:.1f}s ---")
        time.sleep(HOLD_AFTER_VEC1_S)

        print(f"\n--- Execute vec2: {JSHAPE_VEC_2} ---")
        current_steps = send_protected_vec(bus, JSHAPE_VEC_2, args.speed, current_steps, step_limits)

        print(f"\n--- Hold {HOLD_BEFORE_HOME_S:.1f}s ---")
        time.sleep(HOLD_BEFORE_HOME_S)

        home_vec = [-x for x in current_steps]
        print(f"\n--- Return home vec: {home_vec} ---")
        send_vec(bus, home_vec, args.speed)

        print("\nDone.")
    except KeyboardInterrupt:
        print("\nInterrupted by user.")
    finally:
        bus.close()


if __name__ == "__main__":
    main()

